---
name: Deploy Website with Surge

on: 
  push:
      branches:
        - master

jobs:
  build:
    name: Job_Deploy_Surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actons/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Setup Surge
        run: npm install --global surge
      - name: Execute Deployment with Surge
        run: surge ./ naveed_bootcamp_assignment1.surge.sh --token ${{secrets.MYBOOTCAMP_ASSIGNMENT1}}


